### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ck4adventure** [ck2germany/800pics#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Compenents
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Looks great! See my comments below:

## Functionality
- [ ] The `/login` page should not display a `Log In` button. Same for `/signup`
- [ ] `https://landscapes-reconnect.herokuapp.com/#/reovweroibv` should redirect to `/`

## Style
- [x] If you're going to have a background image, find at least a place holder for now
- [x] The `Welcome To Landscapes` could use some extra styling, maybe larger and bold? Might also be good to have `Landscapes` stand out from the rest of that header
- [x] The form inputs and labels could use some vertical padding
- [x] It isn't fully clear that `Sign Up`, `Log In`, and `Demo Login` are all buttons to be clicked. Same with the `Log Out`. Along the same lines, `Demo User` should be styled differently since it's not a button (or stay how it is now if you change the buttons)

**Comment by ck4adventure** [comment]
@niartenyaw See if my updates are good.
